services:
  app:
    build:
      context: .
      target: app
    image: svelte-components:latest
    container_name: svelte-components-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - db
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src

  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - /var/lib/postgresql/data # Persist data

